name: Build VST3

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
          # vst3sdk is currently not supported in CI on macos, see https://github.com/microsoft/vcpkg/pull/41903
          # - macos-latest
          - ubuntu-latest
        config: [debug, release]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'

      - name: Install vcpkg
        run: git clone https://github.com/microsoft/vcpkg.git vcpkg

      - name: Install macOS Dependencies
        if: runner.os == 'macOS'
        run: |
          brew install ninja

      - name: Install Ubuntu Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update && sudo apt install -y \
                libx11-dev libxinerama-dev libxrandr-dev libxcursor-dev libfreetype6-dev libasound2-dev \
                libxcomposite-dev libxext-dev \
                libgl1-mesa-dev libglu1-mesa-dev \
                ninja-build \
                autoconf libtool \
                unzip \
                alsa-utils alsa-base libasound2-dev timidity \
                cmake build-essential

      - name: Configure CMake
        run: cmake --preset vcpkg
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg

      - name: Build
        run: cmake --build --preset ${{ matrix.config  }}

      - name: Validate VST3
        run: cmake --build --target validate_vst3 --preset ${{ matrix.config  }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: JUCE-hello-world-vst3-${{ runner.os }}-${{ matrix.config }}
          path: out/install/VST3/
