name: Build VST3

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        config: [debug, release]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install vcpkg
        run: git clone https://github.com/microsoft/vcpkg.git vcpkg

      - name: Install macOS Dependencies
        if: runner.os == 'macOS'
        run: |
          brew install ninja

      - name: Configure CMake
        run: cmake --preset vcpkg
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg

      - name: Build
        run: cmake --build --preset ${{ matrix.config  }}

      - name: Validate VST3
        run: cmake --build build --target validate_vst3

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: JUCE-hello-world-vst3-${{ runner.os }}-${{ matrix.config }}
          path: out/install/VST3/
